name: Prod Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # GitHub 저장소에서 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Node 설정  
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'  

      # Dependencies 설치
      - name: Install dependencies
        run: npm install
        
      # React 프로젝트 빌드
      - name: Build React App
        run: npm run build

      # EC2에 배포하기 위한 파일 준비
      - name: Prepare artifact
        run: |
          mkdir deployment
          cp -r dist/* deployment/
          
  deploy:
      runs-on: ubuntu-latest
      needs: build
  
      steps:
        # EC2 서버로 SSH 접속을 위해 SSH Key를 설정
        - name: Install SSH key
          uses: webfactory/ssh-agent@v0.9.0
          with:
            host: ${{ secrets.EC2_HOST }}
            ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
            user-name: ${{ secrets.EC2_USERNAME }}
  
        # EC2 서버로 빌드된 파일을 업로드
        - name: Deploy to EC2
          run: |
            scp -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} -r deployment/* ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/www/prod/web/
  
        # SSH로 EC2에 접속하여 웹 서버 재시작 (예: Nginx)
        - name: Restart Nginx
          run: |
            ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
              sudo systemctl restart nginx
            EOF
